run_name: OLMo-1B
seed: 6198
dry_run: true

wandb:
  name: ${run_name}
  project: olmo-small

model:
  d_model: 256
  n_heads: 16
  n_layers: 16
  mlp_ratio: 8
  weight_tying: true
  alibi: false
  rope: true
  flash_attention: false  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell

compile: null  # causes instability on AMD GPUs

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  alpha_f: 0.1

tokenizer:
  identifier: tokenizers/allenai_eleuther-ai-gpt-neox-20b-pii-special.json
  truncate_direction: right

save_folder: ${path.choose:${oc.env:SCRATCH_DIR,no_exist}/checkpoints,/results}/${oc.env:SLURM_JOB_ID,${run_name}}
save_overwrite: false
# Sharded checkpoints (best for restarts)
save_interval: 1000
save_num_checkpoints_to_keep: 9
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 10000
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

max_duration: 739_328  # 3.1T tokens
global_train_batch_size: 2048
device_train_microbatch_size: 8

precision: amp_bf16

fsdp:
  wrapping_strategy: null
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: ${save_interval}
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  # lump all the small datasets together (we still get separate metrics).
  - label: v3-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v3-small-c4_en-validation:
          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
        v3-small-dolma_books-validation:
          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_books/val/part-0-00000.npy
        v3-small-dolma_common-crawl-validation:
          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_common-crawl/val/part-0-00000.npy
        v3-small-dolma_pes2o-validation:
          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_pes2o/val/part-0-00000.npy
        v3-small-dolma_reddit-validation:
          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_reddit/val/part-0-00000.npy
        v3-small-dolma_stack-validation:
          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_stack/val/part-0-00000.npy
        v3-small-dolma_wiki-validation:
          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_wiki/val/part-0-00000.npy
        v3-small-ice-validation:
          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/ice/val/part-0-00000.npy
        v3-small-m2d2_s2orc-validation:
          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/m2d2_s2orc/val/part-0-00000.npy
        v3-small-pile-validation:
          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/pile/val/part-0-00000.npy
        v3-small-wikitext_103-validation:
          - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/wikitext_103/val/part-0-00000.npy

  - label: v2-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v2-small-4chan-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/4chan/val.npy
        v2-small-c4_100_domains-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/c4_100_domains/val.npy
        v2-small-c4_en-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/c4_en/val.npy
        v2-small-gab-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/gab/val.npy
        v2-small-ice-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/ice/val.npy
        v2-small-m2d2_s2orc-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/m2d2_s2orc/val.npy
        v2-small-m2d2_wiki-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/m2d2_wiki/val.npy
        v2-small-manosphere-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/manosphere/val.npy
        v2-small-mc4_en-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/mc4_en/val.npy
        v2-small-pile-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/pile/val.npy
        v2-small-ptb-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/ptb/val.npy
        v2-small-twitterAEE-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/twitterAEE/val.npy
        v2-small-wikitext_103-validation:
        - https://olmo-data.org/eval-data/perplexity/v2_small_gptneox20b/wikitext_103/val.npy

  - label: piqa
    type: downstream

  - label: hellaswag
    type: downstream

  - label: winogrande
    type: downstream

  - label: openbook_qa
    type: downstream

  # - label: boolq  # requires implemention of the pmi_dc matrix
    # type: downstream

  - label: sciq
    type: downstream

  - label: arc_easy
    type: downstream

  # - label: arc_challenge  # requires implemention of the pmi_dc matrix
  #   type: downstream

  - label: copa
    type: downstream

  - label: rte
    type: downstream

  - label: commitment_bank
    type: downstream

  - label: mrpc
    type: downstream

  - label: sst2
    type: downstream

data:
  pad_direction: right
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0
  paths:
    - data/v1_5r2_sample-0000.json.gz
    - data/v1_5r2_sample-0001.json.gz
    - data/v1_5r2_sample-0002.json.gz
    - data/v1_5r2_sample-0003.json.gz
    - data/v1_5r2_sample-0004.json.gz
    - data/v1_5r2_sample-0005.json.gz
    - data/v1_5r2_sample-0006.json.gz
    - data/v1_5r2_sample-0007.json.gz
    - data/v1_5r2_sample-0008.json.gz
    - data/v1_5r2_sample-0009.json.gz
    - data/v1_5r2_sample-0010.json.gz
    - data/v1_5r2_sample-0011.json.gz
    - data/v1_5r2_sample-0012.json.gz
    - data/v1_5r2_sample-0013.json.gz
    - data/v1_5r2_sample-0014.json.gz
    - data/v1_5r2_sample-0015.json.gz
    - data/v1_5r2_sample-0016.json.gz
    - data/v1_5r2_sample-0017.json.gz
    - data/v1_5r2_sample-0018.json.gz
    - data/v1_5r2_sample-0019.json.gz
    - data/v1_5r2_sample-0020.json.gz
    - data/v1_5r2_sample-0021.json.gz
    - data/v1_5r2_sample-0022.json.gz
    - data/v1_5r2_sample-0023.json.gz
    - data/v1_5r2_sample-0024.json.gz
    - data/v1_5r2_sample-0025.json.gz
    - data/v1_5r2_sample-0026.json.gz
    - data/v1_5r2_sample-0027.json.gz
    - data/v1_5r2_sample-0028.json.gz
    - data/v1_5r2_sample-0029.json.gz
    - data/v1_5r2_sample-0030.json.gz
    - data/v1_5r2_sample-0031.json.gz
    - data/v1_5r2_sample-0032.json.gz
    - data/v1_5r2_sample-0033.json.gz
    - data/v1_5r2_sample-0034.json.gz
    - data/v1_5r2_sample-0035.json.gz
    - data/v1_5r2_sample-0036.json.gz
    - data/v1_5r2_sample-0037.json.gz
    - data/v1_5r2_sample-0038.json.gz
    - data/v1_5r2_sample-0039.json.gz
    - data/v1_5r2_sample-0040.json.gz
    - data/v1_5r2_sample-0041.json.gz
    - data/v1_5r2_sample-0042.json.gz
    - data/v1_5r2_sample-0043.json.gz
    - data/v1_5r2_sample-0044.json.gz
    - data/v1_5r2_sample-0045.json.gz
    - data/v1_5r2_sample-0046.json.gz
    - data/v1_5r2_sample-0047.json.gz
    - data/v1_5r2_sample-0048.json.gz
    - data/v1_5r2_sample-0049.json.gz
    - data/v1_5r2_sample-0050.json.gz
    - data/v1_5r2_sample-0051.json.gz
    - data/v1_5r2_sample-0052.json.gz
    - data/v1_5r2_sample-0053.json.gz
    - data/v1_5r2_sample-0054.json.gz
    - data/v1_5r2_sample-0055.json.gz
    - data/v1_5r2_sample-0056.json.gz
    - data/v1_5r2_sample-0057.json.gz
    - data/v1_5r2_sample-0058.json.gz
    - data/v1_5r2_sample-0059.json.gz
    - data/v1_5r2_sample-0060.json.gz
    - data/v1_5r2_sample-0061.json.gz
    - data/v1_5r2_sample-0062.json.gz
    - data/v1_5r2_sample-0063.json.gz
    - data/v1_5r2_sample-0064.json.gz
    - data/v1_5r2_sample-0065.json.gz
    - data/v1_5r2_sample-0066.json.gz
    - data/v1_5r2_sample-0067.json.gz
    - data/v1_5r2_sample-0068.json.gz
    - data/v1_5r2_sample-0069.json.gz
    - data/v1_5r2_sample-0070.json.gz
    - data/v1_5r2_sample-0071.json.gz
    - data/v1_5r2_sample-0072.json.gz
    - data/v1_5r2_sample-0073.json.gz
    - data/v1_5r2_sample-0074.json.gz
    - data/v1_5r2_sample-0075.json.gz
    - data/v1_5r2_sample-0076.json.gz
    - data/v1_5r2_sample-0077.json.gz
    - data/v1_5r2_sample-0078.json.gz
    - data/v1_5r2_sample-0079.json.gz
    - data/v1_5r2_sample-0080.json.gz
    - data/v1_5r2_sample-0081.json.gz
    - data/v1_5r2_sample-0082.json.gz
    - data/v1_5r2_sample-0083.json.gz
    - data/v1_5r2_sample-0084.json.gz
    - data/v1_5r2_sample-0085.json.gz
    - data/v1_5r2_sample-0086.json.gz
    - data/v1_5r2_sample-0087.json.gz
    - data/v1_5r2_sample-0088.json.gz
    - data/v1_5r2_sample-0089.json.gz
    - data/v1_5r2_sample-0090.json.gz
    - data/v1_5r2_sample-0091.json.gz
    - data/v1_5r2_sample-0092.json.gz
    - data/v1_5r2_sample-0093.json.gz
    - data/v1_5r2_sample-0094.json.gz
    - data/v1_5r2_sample-0095.json.gz
    - data/v1_5r2_sample-0096.json.gz
    - data/v1_5r2_sample-0097.json.gz
    - data/v1_5r2_sample-0098.json.gz
    - data/v1_5r2_sample-0099.json.gz
    - data/v1_5r2_sample-0100.json.gz
    - data/v1_5r2_sample-0101.json.gz
    - data/v1_5r2_sample-0102.json.gz